
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihgnfpdshxlylqiqcbav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZ25mcGRzaHhseWxxaXFjYmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NzkwMDIsImV4cCI6MjA1MTA1NTAwMn0.c_wUchivUiPu4oOJQRfIS3xnGz3_Gl5brR6O6Lrbbk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
